### ISSUE TITLE
Link to Office Hours

### ISSUE THREAD

**Issue by aliciabecerraromero** [ics80-fa21/website#3]
https://github.com/ics80-fa21/website/blob/9baaac2152e98119e4c4bd81a06e36544c696143/people.html#L94

Hi Mine, I just realized that I did not provide a link to my Zoom office hours. This is my Personal Meeting Zoom Link: https://uci.zoom.us/j/9496137352?pwd=d1VwY1NkTG5ZdUZ6MGwxTWdPVG96dz09

**Comment by mdogucu** [comment]
Does this meeting require UCI authentication?

**Comment by mdogucu** [comment]
It would good not to require a passcode either.

**Comment by aliciabecerraromero** [comment]
It does not require UCI authentication and I just made sure to disable the need for a passcode.

**Comment by mdogucu** [comment]
It should require UCI authentication so that random people from the
internet cannot join.

**Comment by mdogucu** [comment]
The link you gave without using the passcode portion, still requires a
passcode. It is possible that the meeting link might have changed when you
changed the settings.

**Comment by aliciabecerraromero** [comment]
It was easier to simply make one from scratch. This one should require UCI authentication and has no passcode: https://uci.zoom.us/j/95296060263
